name: Python Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Build Docker image
      run: docker build . -t my-python-app

    - name: Run tests (if applicable)
      # You can add your test commands here
      run: docker run my-python-app pytest

    - name: Push Docker image to registry (if needed)
      # This step pushes the image to a Docker registry like Docker Hub
      # Make sure to set up your Docker Hub credentials as secrets in your repository settings
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push my-python-app
